// <auto-generated />
using System;
using CoreWiki.RazorPages.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CoreWiki.RazorPages.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180803030640_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("CoreWiki.RazorPages.Models.Article", b =>
                {
                    b.Property<string>("Topic")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Published");

                    b.HasKey("Topic");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
